### ISSUE TITLE
[FEATURE] Support async functions

### ISSUE THREAD

**Issue by rachfop** [pycob/pycob#7]
**Is your feature request related to a problem? Please describe.**

I'd like for Pycob to support async functions.
**Describe the solution you'd like**

```python
async def my_page(server_request: cob.Request) -> cob.Page:
    page = cob.Page("My Page")

    username = await server_request.get_username()

    page.add_text(f"Hello {username}!")
    some_function(x + y)
    return page
```
**Describe alternatives you've considered**
Flask supports Async:

```bash
pip install "Flask[async]"
```
**Additional context**

**Comment by zainhoda** [comment]
Hello! We are thinking about separating pages into their own independent UI library that you'd be able to use with any framework you like. 

So you'd do this:
```python
page.to_html() # Returns an HTML string
```

And then you'd use it with Flask or Flask async as necessary. Is that something you'd be interested in?

**Comment by zainhoda** [comment]
Hi @rachfop ! 

We separated out our UI components into their own library so that you could theoretically use them with any web framework: https://www.pyvibe.com/

I haven't really given any thought to whether/how the new approach works with async functions because I haven't really used them. If you have any thoughts on that subject, feel free to let me know!
